name: Survival-Server-System
author: pasi1337#8901
version: 1.0
main: de.luca.main.Main
softdepend: NuVotifier

commands:
   teamchat:
      aliases: [tc]
   gamemode:
      aliases: [gm]
   invsee:
   help:
      aliases: [h]
   msg:
   msgtoggle:
   maintenance:
   clearchat:
      aliases: [cc]
   
   